### ISSUE TITLE
jQuery Maximum call stack size exceeded

### ISSUE THREAD

**Issue by brandontravis** [gromo/jquery.scrollbar#141]
I have a fairly basic implemmentation of jquery.scrollbar on my site, and when resizing the browser I often get an "Uncaught RangeError: Maximum call stack size exceeded."

````
jquery.min.js:2 Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Function.ga.matchesSelector (jquery.min.js:2)
    at Function.r.filter (jquery.min.js:2)
    at E (jquery.min.js:2)
    at a.fn.init.is (jquery.min.js:2)
    at BaseScrollbar._updateScroll (jquery.scrollbar.js:615)
    at BaseScrollbar._updateScroll (jquery.scrollbar.js:645)
    at BaseScrollbar._updateScroll (jquery.scrollbar.js:645)
    at BaseScrollbar._updateScroll (jquery.scrollbar.js:645)
    at BaseScrollbar._updateScroll (jquery.scrollbar.js:645)
ga.matchesSelector @ jquery.min.js:2
r.filter @ jquery.min.js:2
E @ jquery.min.js:2
is @ jquery.min.js:2
_updateScroll @ jquery.scrollbar.js:615
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
jquery.min.js:2 Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Function.camelCase (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:2618)
    at Function.css (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:3:22139)
    at Object.get (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:3:22464)
    at Function.css (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:3:22235)
    at http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:21841
    at T (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:3:544)
    at a.fn.init.r.fn.(anonymous function) [as width] (http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:21576)
    at BaseScrollbar._updateScroll (http://cdnjs.cloudflare.com/ajax/libs/jquery.scrollbar/0.2.11/jquery.scrollbar.js:630:47)
    at BaseScrollbar._updateScroll (http://cdnjs.cloudflare.com/ajax/libs/jquery.scrollbar/0.2.11/jquery.scrollbar.js:645:22)
camelCase @ jquery.min.js:2
css @ jquery.min.js:3
get @ jquery.min.js:3
css @ jquery.min.js:3
(anonymous) @ jquery.min.js:4
T @ jquery.min.js:3
r.fn.(anonymous function) @ jquery.min.js:4
_updateScroll @ jquery.scrollbar.js:630
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
_updateScroll @ jquery.scrollbar.js:645
setTimeout (async)
(anonymous) @ jquery.scrollbar.js:728
(anonymous) @ jquery.scrollbar.js:95
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
````

**Comment by gromo** [comment]
Please, make sure you don't use CSS animations/transitions on you container height/width
